nguage: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
before_script: 
  - npm install -g istanbul
  - npm install mocha --save-dev
  - npm install fs-extra --save-dev
  - npm install chai --save-dev
script: npm run cov
